### ISSUE TITLE
Prepared query wrong number of parameter on 2.9.3

### ISSUE THREAD

**Issue by trasher** [zendframework/zend-db#322]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-db/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-db/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Trying to execute a prepared query with named parameters. Works well with 2.9.2 but fails on 2.9.3.

### Code to reproduce the issue

Something like:
```php
$insert = $zdb->sql->insert(self::TABLE);
$insert->values(
    array(
        'name'  => ':name',
        'value'  => ':value'
    )
);
$stmt = $zdb->sql->prepareStatementForSqlObject($insert);

foreach ($values as $k => $v) {
    $stmt->execute(
        array(
            'name' => $k,
            'value' => $v
        )
    );
}
```

### Expected results

Query success.

### Actual results

Fails with the following exception:
```
==> An exception has been thrown in file tests/units/Preferences.php on line xx:
==> PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239
==> Stack trace:
==> #0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
==> #1 lib/Preferences.php(310): Zend\Db\Adapter\Driver\Pdo\Statement->execute(Array)
[...]
```

Array passed to `Statement::execute()` looks like:
```php
array(
    'name' => 'lang',
    'value' => 'en_US'
)
```

Thank you.

**Comment by michalbundyra** [comment]
This repository has been closed and moved to laminas/laminas-db; a new issue has been opened at https://github.com/laminas/laminas-db/issues/47.
