### ISSUE TITLE
Not a valid magic property for this object.

### ISSUE THREAD

**Issue by kevspadilla** [zendframework/zend-db#327]
- [X] I was not able to find an [open](https://github.com/zendframework/zend-db/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-db/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ ] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

```php
        $sql = $this->TableGateway->getSql();
        $select = $sql->select();
        return $this->TableGateway->selectWith($select);   
```

### Expected results

This should return a resultset.

### Actual results
Not a valid magic property for this object.
```php
#0 ..\vendor\zendframework\zend-db\src\Sql\AbstractSql.php(377): Zend\Db\Sql\Select->__get('subject')
#1 ..\vendor\zendframework\zend-db\src\Sql\AbstractSql.php(57): Zend\Db\Sql\AbstractSql->localizeVariables()
#2 ..\vendor\zendframework\zend-db\src\Sql\AbstractPreparableSql.php(34): Zend\Db\Sql\AbstractSql->buildSqlString(Object(Zend\Db\Adapter\Platform\Mysql), Object(Zend\Db\Adapter\Driver\Pdo\Pdo), Object(Zend\Db\Adapter\ParameterContainer))
#3 ..\vendor\prism\Common\src\Common\Db\Sql\Platform\Mysql\SelectDecorator.php(44): Zend\Db\Sql\AbstractPreparableSql->prepareStatement(Object(Zend\Db\Adapter\Adapter), Object(Zend\Db\Adapter\Driver\Pdo\Statement))
#4 ..\vendor\zendframework\zend-db\src\Sql\Platform\AbstractPlatform.php(88): Common\Db\Sql\Platform\Mysql\SelectDecorator->prepareStatement(Object(Zend\Db\Adapter\Adapter), Object(Zend\Db\Adapter\Driver\Pdo\Statement))
#5 ..\vendor\zendframework\zend-db\src\Sql\Sql.php(130): Zend\Db\Sql\Platform\AbstractPlatform->prepareStatement(Object(Zend\Db\Adapter\Adapter), Object(Zend\Db\Adapter\Driver\Pdo\Statement))
#6 ..\vendor\prism\Common\src\Common\Db\TableGateway\DriTableGateway.php(165): Zend\Db\Sql\Sql->prepareStatementForSqlObject(Object(Common\Db\Sql\Select))
#7 ..\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(208): Common\Db\TableGateway\DriTableGateway->executeSelect(Object(Common\Db\Sql\Select))
#8 ..\vendor\prism\Job\src\Job\Model\JobItemsTable.php(168): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Common\Db\Sql\Select))
```

**Comment by kevspadilla** [comment]
Closing issue, my bad.
